stages:
  data_ingestion:
    cmd: python app.py --stage data_ingestion
    deps:
    - networksecurity/components/data_ingestion.py
    outs:
    - artifacts/NetworkSecurityTrainingPipeline/data_ingestion/feature_store/phishingData.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_ingestion/ingested/test.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_ingestion/ingested/train.csv
  data_validation:
    cmd: python app.py --stage data_validation
    deps:
    - artifacts/NetworkSecurityTrainingPipeline/data_ingestion/ingested/train.csv
    - networksecurity/components/data_validation.py
    outs:
    - artifacts/NetworkSecurityTrainingPipeline/data_validation/drift_report/drift_report.html
    - artifacts/NetworkSecurityTrainingPipeline/data_validation/valid_test/test.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_validation/valid_train/train.csv
  data_transformation:
    cmd: python app.py --stage data_transformation
    deps:
    - artifacts/NetworkSecurityTrainingPipeline/data_validation/valid_test/test.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_validation/valid_train/train.csv
    - networksecurity/components/data_tranformation.py
    outs:
    - artifacts/NetworkSecurityTrainingPipeline/data_transformation/transformed/test.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_transformation/transformed/train.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_transformation/transformed_object/model.pkl
  model_trainer:
    cmd: python app.py --stage model_trainer
    deps:
    - artifacts/NetworkSecurityTrainingPipeline/data_transformation/transformed/test.csv
    - artifacts/NetworkSecurityTrainingPipeline/data_transformation/transformed/train.csv
    - networksecurity/components/model_trainer.py
    outs:
    - artifacts/NetworkSecurityTrainingPipeline/model_trainer/trained_model.pkl
